$gaming_key = F19
bind = , $gaming_key, submap, gaming

# use f19 to go into move gaming mode - in gaming mode there is no CTRL bind.
submap = gaming
source = ~/.config/hypr/config-files/binds.conf
# no ctrl mouse movement
bind = , $gaming_key, submap, default

# exit gaming submap bindings, just in case
submap = default

# ctrl mouse movement
bindm = CTRL, mouse:272,    movewindow
bindm = CTRL, mouse:273,    resizewindow