# WIP
# bind = $triMod,Kp_Left,exec,busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 6500
# bind = $triMod,Kp_Begin,exec,busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 4500
# bind = $triMod,Kp_Right,exec,busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 2500

$terminal = kitty #wezterm  - became shit already in 2025
$fileManager = dolphin
$browser = firefox
$menu = rofi

$mod = ALT

bind = $mod, Q, exec, $terminal
bind = $mod, W, killactive,
bind = $mod, E, exec, $fileManager
bind = $mod, T, togglefloating,
bind = $mod, SPACE, exec, $menu -show drun
bind = $mod, B, exec, $browser
bind = $mod, V, exec, cliphist list | $menu -dmenu | cliphist decode | wl-copy
# bind = $mod, Z, exec, zen
bind = $mod, backspace, exec, pkill waybar || waybar
bind = $mod, S, swapsplit

# For scrolling mode
bind = $mod, period, layoutmsg, move +col
bind = $mod, comma, layoutmsg, swapcol l


# ScreenShots
bind = , PRINT, exec, hyprshot -m region --clipboard-only
bind = $mod, PRINT, exec, hyprshot -m window --clipboard-only
bind = $mod SHIFT, PRINT, exec, hyprshot -m output --clipboard-only

# ctrl + LMB - move
bindm = CTRL, mouse:272,    movewindow
# ctrl + RMB - resize
bindm = CTRL, mouse:273,    resizewindow

# Window manipulation
bind = $mod, F,             fullscreen,
#bind = $mod SHIFT, F,       fakefullscreen,
bind = $mod, P,             pin

# toggle split
bind = $mod, Y, togglesplit

# Change window focus
bind = $mod, up,             movefocus, u
bind = $mod, right,             movefocus, r
bind = $mod, down,             movefocus, d
bind = $mod, left,             movefocus, l

# Window movement (for tiled windows)
bind = $mod SHIFT, left,       movewindow, l
bind = $mod SHIFT, down,       movewindow, d
bind = $mod SHIFT, up,       movewindow, u
bind = $mod SHIFT, right,       movewindow, r

# resize window
#bind = $mod ALT, left,         resizeactive, -200 0
#bind = $mod ALT, down,         resizeactive, 0 200
#bind = $mod ALT, up,         resizeactive, 0 -200
#bind = $mod ALT, right,         resizeactive, 200 0

# Switch workspaces with mod + [0-right]
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move active window to a workspace with mod + SHIFT + [0-9]
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Move window to workspace (without switching to workspace)
bind = $mod CTRL SHIFT, 1,  movetoworkspacesilent, 1
bind = $mod CTRL SHIFT, 2,  movetoworkspacesilent, 2
bind = $mod CTRL SHIFT, 3,  movetoworkspacesilent, 3
bind = $mod CTRL SHIFT, 4,  movetoworkspacesilent, 4
bind = $mod CTRL SHIFT, 5,  movetoworkspacesilent, 5
bind = $mod CTRL SHIFT, 6,  movetoworkspacesilent, 6
bind = $mod CTRL SHIFT, 7,  movetoworkspacesilent, 7
bind = $mod CTRL SHIFT, 8,  movetoworkspacesilent, 8
bind = $mod CTRL SHIFT, 9,  movetoworkspacesilent, 9