#monitor=HDMI-A-1,5120x1440@144.00,auto,1

#for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps

#for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons   
#you will need to set dark theme for qt apps from kde more difficult thans with gnome :D:
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps# Theme

input {
  kb_layout = us,ru
  follow_mouse = 2
  # dont need it, cause we use binding for layout changes
  #kb_options = grp:alt_shift_toggle

  #sensitivity = -0.1 # -1.0 - 1.0, 0 means no modification.
  # accel_profile = flat
  force_no_accel = 1
}

ecosystem {
  no_update_news = true
}

# layout change on alt shift
bindrlt = ALT SHIFT, Alt_L, exec, hyprctl switchxkblayout all next

general {
  gaps_in = 3
  gaps_out = 7
  border_size = 4

  resize_on_border = false
  layout = dwindle
}

decoration {
  rounding = 10
  active_opacity = 0.65
  inactive_opacity = 0.65
  dim_inactive = false
  dim_strength = 0.4

  blur {
    enabled = true
    size = 8
    passes = 4
    new_optimizations = on
  }
}

animations {
  enabled = true

  # bezier = myBezier, 0.05, 0.9, 0.1, 1.05

  # animation = windows, 1, 7, myBezier
  # animation = windowsOut, 1, 7, default, popin 80%
  # animation = border, 1, 10, default
  # animation = borderangle, 1, 8, default
  # animation = fade, 1, 7, default
  # animation = workspaces, 1, 6, default

  bezier = myBezier, 0.10, 0.9, 0.1, 1.05

  animation = windows, 1, 5, myBezier, popin
  animation = windowsOut, 1, 5, myBezier, popin 80%
  animation = border, 1, 10, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, default
}

dwindle {
  pseudotile = true
  preserve_split = true
  smart_split = true
}

master {
  new_status = master
}

misc {
  force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}