# Make file picker windows floating
windowrulev2 = float, center, title:^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename), class:^(.*)$
windowrulev2 = float, center, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, center, class:(Xdg-desktop-portal-gtk)
windowrulev2 = float, center, class:(xdg-desktop-portal-hyperland)
windowrulev2 = float, center, class:(Xdg-desktop-portal-hyperland)

# make rofi popin and dim, and blur
layerrule = animation popin 90%, rofi
layerrule = blur, rofi
layerrule = dimaround, rofi