# Make file picker windows floating
windowrulev2 = float, center, title:^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename), class:^(.*)$
windowrulev2 = float, center, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, center, class:(Xdg-desktop-portal-gtk)
windowrulev2 = float, center, class:(xdg-desktop-portal-hyperland)
windowrulev2 = float, center, class:(Xdg-desktop-portal-hyperland)

# trying to fix lags
windowrulev2 = renderunfocused, class:^(godot)$
windowrulev2 = renderunfocused, class:^(minecraft)$
windowrulev2 = renderunfocused, class:^(wine)$
windowrulev2 = renderunfocused, class:^(steam_app_.*)$

# make AmneziaVPN window floating and center
windowrulev2 = float, center, title:^(AmneziaVPN)$

# make rofi popin and dim, and blur
layerrule = animation popin 90%, rofi
layerrule = blur, rofi
layerrule = dimaround, rofi